#!/usr/bin/env node
const commands = require('./commands');

const yargs = require('yargs')
  .usage('$0 <cmd> [args]')
  .command('hello [name]', 'welcome ter yargs!', (yargs) => {
      yargs.positional('name', {
        type: 'string',
        default: 'Cambi',
        describe: 'the name to say hello to'
      })
    },
    function (argv) {
      console.log('hello', argv.name, 'welcome to yargs!')
    })
  .command('completion-script', 'prints the completion script that you can use to enable automatic completion', (yargs) => {}, (args) => {
    yargs.showCompletionScript();
    })
  .command('login', '', (yargs) => {
      yargs
      .command('user <username>', 'Login to your github account and retrieve an access token.', (yargs) => {
        yargs
        .usage('$0 user <username>')
        .positional('username', {
          type: 'string',
          describe: 'The username that you would like to use to log into github',
          conflicts: ['browser', 'token']
        })
      })
      .command('browser', 'Configure an access token for github.', (yargs) => {
        yargs
        .usage('$0 browser')
      })
      .command('token <token>', 'Configure an access token for github.', (yargs) => {
        yargs
        .usage('$0 token <token>')
        .positional('token', {
          type: 'string',
          describe: 'A token generated by github. \nDepending on the level of access, some features may not work correctly.',
          conflicts: ['browser', 'username']
        })
      })
    })
  .strict()
  .help()
  .argv;

switch(yargs._[0]) {
  case 'login':
    commands.login(yargs);
    break;
}